name: Build OpenSearch Protobufs PYTHON Artifacts

on:
  pull_request:

jobs:
  build-protobufs-python:
    runs-on: ubuntu-latest
    if: github.repository == 'opensearch-project/opensearch-protobufs'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: 21
      - name: build protobufs python
        run: bazel build //:python_schemas //:python_services
