name: Build and Publish Snapshots to Maven

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'maven_publish1'
jobs:
  build-and-publish-snapshots:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: temurin # Temurin is a distribution of adoptium
          java-version: 21
      - name: Install Protocol Buffers Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - uses: bazelbuild/setup-bazelisk@v2
        with:
          bazel-version: 5.4.1
      - uses: actions/checkout@v3

#      - uses: aws-actions/configure-aws-credentials@v1
#        with:
#          role-to-assume: ${{ secrets.PUBLISH_SNAPSHOTS_ROLE }}
#          aws-region: us-east-1
      - name: publish snapshots to maven
        run: |
          export SONATYPE_USERNAME=abc
          export SONATYPE_PASSWORD=abc
          ./tools/java/package_proto_jar.sh